Repository Onemind-Services-LLC/netbox-paas, pull requests merged in 2024-01, with the labels that each got.

#5 pyproject.toml file added
  configuration/configuration.py
  netbox_cloud_pilot/constants.py
  netbox_cloud_pilot/forms.py
  netbox_cloud_pilot/iaas.py
  netbox_cloud_pilot/models.py
  netbox_cloud_pilot/nb_settings.py
  netbox_cloud_pilot/utils.py
  netbox_cloud_pilot/views.py
  pyproject.toml
  setup.py
Labels: type: feature

#7 Fix plugin config and setup.py file
  netbox_cloud_pilot/__init__.py
  setup.py
Labels: type: bug

#8 Release v0.0.2
  .github/workflows/ci.yml
  README.md
  configuration/configuration.py
  netbox_cloud_pilot/__init__.py
  netbox_cloud_pilot/constants.py
  netbox_cloud_pilot/forms.py
  netbox_cloud_pilot/iaas.py
  netbox_cloud_pilot/models.py
  netbox_cloud_pilot/nb_settings.py
  netbox_cloud_pilot/templates/netbox_cloud_pilot/inc/plugin_store.html
  netbox_cloud_pilot/templates/netbox_cloud_pilot/plugins_store.html
  netbox_cloud_pilot/utils.py
  netbox_cloud_pilot/views.py
  pyproject.toml
  setup.py
Labels: type: maintenance

#9 Release v0.0.3
  netbox_cloud_pilot/iaas.py
  netbox_cloud_pilot/migrations/0001_initial.py
  netbox_cloud_pilot/migrations/0002_netboxconfiguration_license.py
  netbox_cloud_pilot/models.py
  netbox_cloud_pilot/views.py
  setup.py
Labels: type: maintenance

#10 Release v0.1.0
  Dockerfile
  README.md
  docker-compose.yml
  netbox_cloud_pilot/__init__.py
  netbox_cloud_pilot/constants.py
  netbox_cloud_pilot/forms.py
  netbox_cloud_pilot/iaas.py
  netbox_cloud_pilot/templates/netbox_cloud_pilot/inc/plugin_store.html
  netbox_cloud_pilot/templates/netbox_cloud_pilot/plugin_disable.html
  netbox_cloud_pilot/templates/netbox_cloud_pilot/plugin_enable.html
  netbox_cloud_pilot/views.py
  setup.py
Labels: type: maintenance

#11 Fixed running collectstatic during upgrade
  Dockerfile
  netbox_cloud_pilot/iaas.py
  setup.py
Labels: type: bug

#12 Fixed license key max value
  Dockerfile
  netbox_cloud_pilot/migrations/0001_initial.py
  netbox_cloud_pilot/models.py
  setup.py
Labels: type: bug

#13 Fixed license validation error
  netbox_cloud_pilot/models.py
  setup.py
Labels: type: bug

#14 Fixed minor version upgrade process
  netbox_cloud_pilot/iaas.py
  setup.py
Labels: type: bug

#17 Release v0.1.5
  docker-compose.yml
  netbox_cloud_pilot/__init__.py
  netbox_cloud_pilot/forms.py
  netbox_cloud_pilot/iaas.py
  netbox_cloud_pilot/migrations/0001_initial.py
  netbox_cloud_pilot/models.py
  setup.py
Labels: type: maintenance

#18 Fixed plugin install and uninstall from all nodes
  netbox_cloud_pilot/iaas.py
  setup.py
Labels: type: bug

#19 Added more checks in forms
  netbox_cloud_pilot/forms.py
  setup.py
Labels: type: feature

#20 Updated upgrade views
  netbox_cloud_pilot/forms.py
  netbox_cloud_pilot/iaas.py
  netbox_cloud_pilot/templates/netbox_cloud_pilot/inc/plugin_store.html
  netbox_cloud_pilot/utils.py
  netbox_cloud_pilot/views.py
  setup.py
Labels: type: feature

#21 Release v0.1.9
  netbox_cloud_pilot/forms.py
  netbox_cloud_pilot/models.py
  setup.py
Labels: type: maintenance

#22 Optimized apply settings
  netbox_cloud_pilot/models.py
  setup.py
Labels: type: feature

#23 Fixed config file write operation
  netbox_cloud_pilot/models.py
  setup.py
Labels: type: bug

#24 Fixed git install for all nodes
  netbox_cloud_pilot/iaas.py
  setup.py
Labels: type: bug

#25 Added plugin management APIs
  netbox_cloud_pilot/api/serializers.py
  netbox_cloud_pilot/api/urls.py
  netbox_cloud_pilot/api/views.py
  netbox_cloud_pilot/utils.py
  setup.py
Labels: type: feature

#26 Fixed plugin management APIs
  netbox_cloud_pilot/api/views.py
  setup.py
Labels: type: bug

#27 Fixed upgrade env app id
  netbox_cloud_pilot/api/views.py
  netbox_cloud_pilot/iaas.py
  setup.py
Labels: type: bug

#28 Fixed restarting nodes to avoid volume read errors
  netbox_cloud_pilot/iaas.py
  setup.py
Labels: type: bug

#30 Allow license blank in API POST method
  Dockerfile
  docker-compose.yml
  netbox_cloud_pilot/api/serializers.py
Labels: type: bug

#31 Allow license blank on API for dev branch
  netbox_cloud_pilot/api/serializers.py
Labels: type: bug

#32 Release v0.1.17
  netbox_cloud_pilot/api/serializers.py
  setup.py
Labels: type: maintenance
